### ISSUE TITLE
转换的amr全部是噪声

### ISSUE THREAD

**Issue by stjack** [WuFengXue/WeChatVoiceCodec#1]
您好。我成功编译了您的apk，并且使用您的amr通过hook进行语音发送，但是发送收到的声音全部是噪声。很奇怪的是，如果用你做的一个pcm（AMR格式）发送就一切正常。可以问下什么原因，怎么debug么？谢谢

**Comment by WuFengXue** [comment]
嗨，这个库是有验证过（虽然有半年多没有用最新的微信测试了）的，照理应该是没有问题的。

我看您后面把 issue 关闭了，**建议补充下关闭的原因，因为其他人可能也会遇到类似的问题。**

有其他问题也欢迎提出来，我在能力范围内会尽量给予解答。
