### ISSUE TITLE
关于silk音频参数的问题

### ISSUE THREAD

**Issue by voyagerw** [WuFengXue/WeChatVoiceCodec#3]
你好，请问下silk文件头中没有音频的采样率或通道数这类参数信息吗？解码时是只能手动指定？在你的博客里对silk文件头进行描述时，似乎并没有关于这些的介绍。
如果知道的话，还请能够介绍一下，感觉网上能够找到的关于silk的信息和文档就只有那个SDK源码，其他的信息都不好找。

**Comment by WuFengXue** [comment]
您好，如我这篇文章《[微信语音编解码实现（二）—— 支持微信语音](https://wufengxue.github.io/2019/04/17/wechat-voice-codec-amr.html)》中写的，silk 的文件头中是不带这些参数的（是否会放在数据部分，只能自己翻翻源码了）。
个人的理解，silk 编解码是结对使用的，所以不带这些参数是不会有影响的。
当前有用到silk，我个人知道的也主要是腾讯系的产品。
因为我们当初是跟微信相关的，所以参数直接采用网上其他项目的参数了，具体参数选择的根据我也没能掌握。
（参见《[微信语音编解码实现（四）—— 整合 so 库](https://wufengxue.github.io/2019/06/29/wechat-voice-codec-lib.html)》的**第5节 回顾与后续**）

个人的建议：
1、如果是想结对使用，可以直接使用微信的参数，加密部分可以调成自己的
2、如果是针对逆向安全相关的，只能借鉴市面已有的方案，或者按参数尝试，或者翻墙看看外网是否有更多的资料

**Comment by voyagerw** [comment]
好的，还是挺感谢你的回复



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月10日(周二) 下午3:57
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [WuFengXue/WeChatVoiceCodec] 关于silk音频参数的问题 (#3)




 
您好，如我这篇文章《微信语音编解码实现（二）—— 支持微信语音》中写的，silk 的文件头中是不带这些参数的（是否会放在数据部分，只能自己翻翻源码了）。
 个人的理解，silk 编解码是结对使用的，所以不带这些参数是不会有影响的。
 当前有用到silk，我个人知道的也主要是腾讯系的产品。
 因为我们当初是跟微信相关的，所以参数直接采用网上其他项目的参数了，具体参数选择的根据我也没能掌握。
 （参见《微信语音编解码实现（四）—— 整合 so 库》的第5节 回顾与后续）
 
个人的建议：
 1、如果是想结对使用，可以直接使用微信的参数，加密部分可以调成自己的
 2、如果是针对逆向安全相关的，只能借鉴市面已有的方案，或者按参数尝试，或者翻墙看看外网是否有更多的资料
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by WuFengXue** [comment]
不客气~

搜索找不到资料的时候，可以发散一点，把安卓的限定拿掉，可能会有新的发现。
我刚刚又搜了一下，看到了两篇文章：

- 《[从微信中提取语音文件，并转换成文字的全自动化解决方案](https://iosre.com/t/topic/3199)》（iOS）
- 《[解码转换QQ微信的SILK v3编码音频为MP3或其他格式](https://kn007.net/topics/decoding-qq-wechat-silk-v3-encoded-audio-to-mp3-or-other-formats/)》（Windows）

并不是直接的答案，只是作为示例，如果你最终找到了答案，希望你也能告诉我哈
