### ISSUE TITLE
多线程下调用amr转mp3函数闪退

### ISSUE THREAD

**Issue by pslilysm** [WuFengXue/WeChatVoiceCodec#4]
这是堆栈
![image](https://user-images.githubusercontent.com/41366450/147240246-8396cf07-d1ef-42d1-ac05-15d4b59f307c.png)

**Comment by WuFengXue** [comment]
[微信语音编解码实现（五）—— 工作线程编解码](https://wufengxue.github.io/2020/06/22/wechat-voice-codec-SEGV_MAPERR.html)

这个问题之前已经修复过了，具体请参考这篇文章

**Comment by pslilysm** [comment]
您好，是有好几个线程同时调用该函数时出现的问题，我用的WeChatVoiceCodec版本是1.0.2。看了您文章的demo，都是单线程在调用，单线程我自己也测试过确实没问题的。

**Comment by WuFengXue** [comment]
我刚刚试了下，是可以正常工作的。

多个线程同时处理的时候，中间文件和目标文件需要取不同的名字，不然多个线程同时写同一个文件可能会导致线程安全问题。

我创建了一个【multiThreadDecodeTest】分支，你可以跑跑看。
（具体修改内容可以看[这个提交](https://github.com/WuFengXue/WeChatVoiceCodec/commit/fec334926fc220af9e0c7ae30bace25719fddb3c)）

**Comment by WuFengXue** [comment]
半个多月没有新的问题，暂定该问题已经没有疑义，后续如果仍有其他问题，请提新的 issue
