### ISSUE TITLE
1.0.2是发布在jcenter吗？jcenter关闭了。。。

### ISSUE THREAD

**Issue by kiddkyd2** [WuFengXue/WeChatVoiceCodec#5]
gradle总是提示拉不回来这个包。。。

**Comment by WuFengXue** [comment]
是放【jcenter】，先用模块导入或 aar 导入，我后续有时间了再上传到其他仓库哈

**Comment by WuFengXue** [comment]
已部署到 MavenCentral，请查阅最新的 README
（因 1.0.2 部署时依赖未处理好，升级了一个版本，最新版本为 1.0.3）
